let i = 1;
export const ProjectData = [
  {
    id: i++,
    src: "/img/YelpCamp.png",
    title: "YelpCamp",
    description: "descrition1",
    tags: [
      "Node",
      "Express",
      "MongoDB",
      "CRUD",
      "RESTful API",
      "Google Cloud Platform",
      "Auth",
      "Mapbox",
    ],
    demo: "https://yelpcamp-zbpbgz6wjq-de.a.run.app/",
    code: "https://github.com/Welin-Chen/YelpCamp/tree/master",
  },
  {
    id: i++,
    src: "/img/netflix.png",
    title: "Netflix-clone",
    description: "descrition1",
    tags: ["React", "Firebase", "MUI"],
    demo: "https://netflix-clone-six-orpin.vercel.app/",
    code: "https://github.com/Welin-Chen/netflix-clone",
  },
  {
    id: i++,
    src: "/img/covid-19.png",
    title: "Covid-19 Tracker",
    description: "descrition1",
    tags: ["React", "Firebase", "MUI", "Leaflet"],
    demo: "https://covid-19-tracker-blond.vercel.app/",
    code: "https://github.com/Welin-Chen/covid-19-tracker",
  },
  {
    id: i++,
    src: "/img/amazon.png",
    title: "Amazone-clone",
    description: "React MUI Stripe Firebase Authentication",
    tags: ["React", "Firebase", "MUI", "Auth"],
    demo: "https://amazon-clone-gutc6z8f7-welin-chen.vercel.app/",
    code: "https://github.com/Welin-Chen/amazon-clone",
  },

  {
    id: i++,
    src: "/img/spotify.png",
    title: "Spotify-clone",
    description: "descrition1",
    tags: ["React", "Firebase", "MUI", "Auth"],
    demo: "https://spotify-clone-theta-ten.vercel.app/",
    code: "https://github.com/Welin-Chen/spotify-clone",
  },
  {
    id: i++,
    src: "/img/airbnb.png",
    title: "Airbnb-clone",
    description: "descrition1",
    tags: ["React", "Firebase", "MUI"],
    demo: "https://airbnb-clone-tau-jade.vercel.app/",
    code: "https://github.com/Welin-Chen/airbnb-clone",
  },
  {
    id: i++,
    src: "/img/hulu.png",
    title: "Hulu-clone",
    description: "descrition1",
    tags: ["Next", "Tailwindcss", "Vercel"],
    demo: "https://hulu-clone-coral-seven.vercel.app/",
    code: "https://github.com/Welin-Chen/hulu-clone",
  },
  {
    id: i++,
    src: "/img/messenger.png",
    title: "Facebook-messenger-clone",
    description: "descrition1",
    tags: ["React", "Firebase", "MUI"],
    demo: "https://facebook-messenger-clone-rouge.vercel.app/",
    code: "https://github.com/Welin-Chen/facebook-messenger-clone",
  },
  {
    id: i++,
    src: "/img/todo_py_flask.png",
    title: "ToDo List",
    description: "descrition1",
    tags: ["Python", "Flask", "SQLite", "GCP"],
    demo: "https://flask-todo-ecsxamgaha-de.a.run.app/",
    code: "https://github.com/Welin-Chen/flask-todo",
  },
];
