export const ProjectData = [
  {
    id: 1,
    src: "/img/amazon.png",
    title: "Amazone-clone",
    description: "React MUI Stripe Firebase Authentication",
    tags: ["React", "Firebase", "MUI", "Auth"],
    demo: "https://amazon-clone-gutc6z8f7-welin-chen.vercel.app/",
    code: "https://github.com/Welin-Chen/amazon-clone",
  },
  {
    id: 2,
    src: "/img/netflix.png",
    title: "Netflix-clone",
    description: "descrition1",
    tags: ["React", "Firebase", "MUI"],
    demo: "https://netflix-clone-six-orpin.vercel.app/",
    code: "https://github.com/Welin-Chen/netflix-clone",
  },
  {
    id: 3,
    src: "/img/covid-19.png",
    title: "Covid-19 Tracker",
    description: "descrition1",
    tags: ["React", "Firebase", "MUI", "Leaflet"],
    demo: "https://covid-19-tracker-blond.vercel.app/",
    code: "https://github.com/Welin-Chen/covid-19-tracker",
  },
  {
    id: 4,
    src: "/img/spotify.png",
    title: "Spotify-clone",
    description: "descrition1",
    tags: ["React", "Firebase", "MUI", "Auth"],
    demo: "https://spotify-clone-theta-ten.vercel.app/",
    code: "https://github.com/Welin-Chen/spotify-clone",
  },
  {
    id: 5,
    src: "/img/airbnb.png",
    title: "Airbnb-clone",
    description: "descrition1",
    tags: ["React", "Firebase", "MUI"],
    demo: "https://airbnb-clone-tau-jade.vercel.app/",
    code: "https://github.com/Welin-Chen/airbnb-clone",
  },
  {
    id: 6,
    src: "/img/hulu.png",
    title: "Hulu-clone",
    description: "descrition1",
    tags: ["Next", "Tailwindcss", "Vercel"],
    demo: "https://hulu-clone-coral-seven.vercel.app/",
    code: "https://github.com/Welin-Chen/hulu-clone",
  },
  {
    id: 7,
    src: "/img/messenger.png",
    title: "Facebook-messenger-clone",
    description: "descrition1",
    tags: ["React", "Firebase", "MUI"],
    demo: "https://facebook-messenger-clone-rouge.vercel.app/",
    code: "https://github.com/Welin-Chen/facebook-messenger-clone",
  },
  {
    id: 8,
    src: "/img/YelpCamp.png",
    title: "YelpCamp",
    description: "descrition1",
    tags: [
      "Node",
      "CRUD",
      "MongoDB",
      "Express",
      "Boostrap",
      "Heroku",
      "Auth",
      "Mapbox",
    ],
    demo: "https://still-badlands-39239.herokuapp.com/campgrounds",
    code: "https://github.com/Welin-Chen/Web_Development_Bootcamp_2022_ColtSteele/tree/master/YelpCamp",
  },
];
